### ISSUE TITLE
Having trouble with many partitions of the same cinematic

### ISSUE THREAD

**Issue by ghost** [Surihix/FFXIIIWMPtool#2]
![imagem_2024-11-09_164635518](https://github.com/user-attachments/assets/e6f861ac-8d3b-490d-8477-b052ac4849bb)

when i extract a cutscene it comes out with this many archives but i can open only 1, the others ones when i try to open it says "Not a bink file", in the propieties says it is tho and the cutscene that i can open doesnt have the full tracks of audio in it.

Do you know how to fix it?

**Comment by Surihix** [comment]
Did you use the correct movie_items .wdb file when extracting the archive files ?

If you are trying to extract wmp archive files that have an '_us' suffix in the filename, then you have to use the `movie_items_us.win32.wdb` file. 

If you are trying to extract wmp archive files that do not have an '_us' suffix in the filename, then you have to use the `movie_items.win32.wdb` file.

**Comment by ghost** [comment]
Worked ty

**Comment by Surihix** [comment]
nice. I will close this issue then as you have solved the problem.

**Comment by ghost** [comment]
alright
